### ISSUE TITLE
Deployment issue on Heroku

### ISSUE THREAD

**Issue by EPFLRQN** [synzen/Discord.RSS-Web#3]
![image](https://user-images.githubusercontent.com/45467260/79484386-24b30700-8046-11ea-9b58-b1564f7e53af.png)

**Comment by synzen** [comment]
Thanks for the report. Heroku is no longer supported within this repo since discord.rss is a peer dependency (https://github.com/synzen/Discord.RSS-Web/commit/de7f57ef198da044c75ac2962363be9e932e59d6). 

It can be started in Heroku within the clone repo now https://github.com/synzen/Discord.RSS-Clone.
